### ISSUE TITLE
chrX pipeline 

### ISSUE THREAD

**Issue by arvkevi** [pgxcentre/genipe#53]
Hello, thank you for developing this tool. Could you please help me understand how to impute chrX? I've downloaded the chrX reference files from [here](https://mathgen.stats.ox.ac.uk/impute/1000GP_Phase3.html)

This command is raising an error:
```
genipe-launcher 
--chrom 23
--bfile /home/kevin/data/member.plink.gt  
--shapeit-bin /home/kevin/impbin/shapeit 
--impute2-bin /home/kevin/impbin/impute2  
--plink-bin /home/kevin/impbin/plink  
--reference /home/kevin/hg19/hg19.fasta 
--hap-nonPAR /home/kevin/1000GP_Phase3_chrX/1000GP_Phase3_chrX_NONPAR.hap.gz 
--hap-PAR1 /home/kevin/1000GP_Phase3_chrX/1000GP_Phase3_chrX_PAR1.hap.gz 
--hap-PAR2 /home/kevin/1000GP_Phase3_chrX/1000GP_Phase3_chrX_PAR2.hap.gz 
--legend-nonPAR /home/kevin/1000GP_Phase3_chrX/1000GP_Phase3_chrX_NONPAR.legend.gz 
--legend-PAR1 /home/kevin/1000GP_Phase3_chrX/1000GP_Phase3_chrX_PAR1.legend.gz 
--legend-PAR2 /home/kevin/1000GP_Phase3_chrX/1000GP_Phase3_chrX_PAR2.legend.gz 
--map-nonPAR /home/kevin/1000GP_Phase3_chrX/genetic_map_chrX_nonPAR_combined_b37.txt 
--map-PAR1 /home/kevin/1000GP_Phase3_chrX/genetic_map_chrX_PAR1_combined_b37.txt 
--map-PAR2 /home/kevin/1000GP_Phase3_chrX/genetic_map_chrX_PAR2_combined_b37.txt
--filtering-rules 'ALL<0.01 ALL>0.99' 
--segment-length 5e06 
--impute2-extra '-nind 1' 
--output-dir /home/kevin/outdir/chr23 
--sample-file /home/kevin/1000GP_Phase3/1000GP_Phase3.sample
```
```
[2018-10-28 12:31:15 INFO] Task 'plink missing rate': already performed in 0 seconds
[2018-10-28 12:31:15 INFO] Done computing missing rate
[2018-10-28 12:31:15 INFO] Reading the missing rate
[2018-10-28 12:31:16 ERROR] 'NoneType' object has no attribute 'format'
Traceback (most recent call last):
  File "/home/kevin/imputer/imputerenv/bin/genipe-launcher", line 11, in <module>
    load_entry_point('genipe', 'console_scripts', 'genipe-launcher')()
  File "/home/kevin/genipe/genipe/pipeline/cli.py", line 197, in main
    options=args,
  File "/home/kevin/genipe/genipe/pipeline/cli.py", line 989, in check_strand
    map_filename = options.map_template.format(chrom=chrom)
AttributeError: 'NoneType' object has no attribute 'format'
```
It looks like it's expecting `map-template`, `hap-template`, and `legend-template` to be provided, so I tried supplying the appropriate `nonPAR` files for each of these and the pipeline fails in phasing:

```
[2018-10-28 12:42:38 INFO] Phasing markers
[2018-10-28 12:42:38 INFO] Executing SHAPEIT phase chr23
[2018-10-28 12:42:38 ERROR] problem executing SHAPEIT phase chr23
```

```
$ less chr23.alignments.log
...
ERROR: Reference and Main panels are not well aligned:
  * #Missing sites in reference panel = 1344
  * #Misaligned sites between panels = 7712
  * #Multiple alignments between panels = 0
```

Thanks again, I'd appreciate any help you could offer.

**Comment by lemieuxl** [comment]
We recently ran only chromosome 23 using the pipeline and it worked. What I would suggest is to delete the resulting directory and start over (as *genipe* skips steps that were previously run, which ended in an error).

If the pipeline still fails, could you send me (via email) the BIM file, so that I can have a look at the variations on chromosome 23 and try to find a fix?

Also, I saw an error in your command line (not related to the problem here discussed, but which will affect the imputation part of the pipeline). The filtering parameters should be separated (as shown in [*genipe*'s tutorial](http://pgxcentre.github.io/genipe/tutorials/tutorial_genipe.html#executing-the-pipeline) and in [*impute2*'s example](https://mathgen.stats.ox.ac.uk/impute/impute_v2.html#ex4)).

Hence, the command should be:

```bash
--filtering-rules 'ALL<0.01' 'ALL>0.99'
```

**Comment by sureman** [comment]
I'm having the exact same issue.  I was able to get a bit farther by specifying `--map-template`, `--hap-template`, and `--legend-template` as @arvkevi mentioned which seems odd since the hap, legend and map files were already specified with `--hap-nonPAR`, etc but it did ultimately fail at the phasing step.  I was not able to specify the NONPAR reference files with the `--shapeit-extra -R` command, so I was wondering if someone could post this portion of the command.  Thanks!

**Comment by lemieuxl** [comment]
Hi @sureman

The best way to make sure everything runs smoothly is to provide at least the *hap*, *legend* and *map* templates and the *sample* file for the autosomes (as in the tutorial script).

```bash
...
    --hap-template '/data/impute2_files/1000GP_Phase3_chr{chrom}.hap.gz' \
    --legend-template '/data/impute2_files/1000GP_Phase3_chr{chrom}.legend.gz' \
    --map-template '/data/impute2_files/genetic_map_chr{chrom}_combined_b37.txt' \
    --sample-file /data/impute2_files/1000GP_Phase3.sample
...
```

Making sure the sample file is the same for autosomes and chrX (which is the case for the original IMPUTE2 reference files), you can specify the *map*, *legend* and *hap* files for the 3 regions.

```bash
...
    --hap-nonPAR /data/1000GP_Phase3_chrX_NONPAR.hap.gz \
    --hap-PAR1 /data/1000GP_Phase3_chrX_PAR1.hap.gz \
    --hap-PAR2 /data/1000GP_Phase3_chrX_PAR2.hap.gz \
    --legend-nonPAR /data/1000GP_Phase3_chrX_NONPAR.legend.gz \
    --legend-PAR1 /data/1000GP_Phase3_chrX_PAR1.legend.gz \
    --legend-PAR2 /data/1000GP_Phase3_chrX_PAR2.legend.gz \
    --map-nonPAR /data/genetic_map_chrX_nonPAR_combined_b37.txt \
    --map-PAR1 /data/genetic_map_chrX_PAR1_combined_b37.txt \
    --map-PAR2 /data/genetic_map_chrX_PAR2_combined_b37.txt \
...
```

You shouldn't need to specify the reference file using shapeit's `-R` option. What kind of error are you getting?
