### ISSUE TITLE
Unreleased version of BioPython (1.73) required 

### ISSUE THREAD

**Issue by LeoBman** [pgxcentre/genipe#54]
I installed genipe using conda and when trying to run it get the following error: 

```
"BioPython >= 1.73 must be installed to read block gzip files.")
ImportError: BioPython >= 1.73 must be installed to read block gzip files.
```

However, this version of biopython is not yet released [AFAIK](https://github.com/biopython/biopython/blob/master/NEWS.rst#in-progress-not-yet-released-biopython-173).

Any advice on how to move forward?

-----------------------------

Full input, stdout & error:
```
genipe-launcher \
     --chrom autosomes \
array.genotype/SPARK.30K.genotype.release_set.hg19.plink \TA/SPARK_Freeze_Three/ 
     --shapeit-bin $HOME/bin/shapeit \
     --impute2-bin $HOME/bin/impute2 \
     --plink-bin $HOME/bin/plink \
eq/hg19.fa.gz \ce /Dedicated/jmichaelson-wdata/bcbio-dna/genomes/Hsapiens/hg19/s 
ase3/1000GP_Phase3_chr{chrom}.hap.gz \elson-sdata/1KG/impute_reference/1000GP_Ph 
_Phase3/1000GP_Phase3_chr{chrom}.legend.gz \on-sdata/1KG/impute_reference/1000GP 
ase3/genetic_map_chr{chrom}_combined_b37.txt \ata/1KG/impute_reference/1000GP_Ph 
se3/1000GP_Phase3.sample \ated/jmichaelson-sdata/1KG/impute_reference/1000GP_Pha 
     --filtering-rules 'ALL<0.01' 'ALL>0.99' \
     --thread 50 \
     --report-title "SPARK_Freeze_Three_imputed" \
     --report-number "SPARK Report"
[2018-11-26 13:56:12 INFO] Logging everything into 'genipe/genipe.log'
[2018-11-26 13:56:12 INFO] Program arguments: --chrom autosomes --bfile /Dedicated/jmichaelson-sdata/Simons/SPARK/DATA/SPARK_Freeze_Three/array.genotype/SPARK.30K.genotype.release_set.hg19.plink --shapeit-bin /Users/lbrueggeman/bin/shapeit --impute2-bin /Users/lbrueggeman/bin/impute2 --plink-bin /Users/lbrueggeman/bin/plink --reference /Dedicated/jmichaelson-wdata/bcbio-dna/genomes/Hsapiens/hg19/seq/hg19.fa.gz --hap-template '/Dedicated/jmichaelson-sdata/1KG/impute_reference/1000GP_Phase3/1000GP_Phase3_chr{chrom}.hap.gz' --legend-template '/Dedicated/jmichaelson-sdata/1KG/impute_reference/1000GP_Phase3/1000GP_Phase3_chr{chrom}.legend.gz' --map-template '/Dedicated/jmichaelson-sdata/1KG/impute_reference/1000GP_Phase3/genetic_map_chr{chrom}_combined_b37.txt' --sample-file /Dedicated/jmichaelson-sdata/1KG/impute_reference/1000GP_Phase3/1000GP_Phase3.sample --filtering-rules 'ALL<0.01' 'ALL>0.99' --thread 50 --report-title SPARK_Freeze_Three_imputed --report-number 'SPARK Report'
[2018-11-26 13:56:12 INFO] Connecting to DB 'genipe/tasks.db'
[2018-11-26 13:56:12 INFO] Will be using SHAPEIT version v2.r904
[2018-11-26 13:56:12 INFO] Will be using IMPUTE2 version 2.3.2
[2018-11-26 13:56:12 INFO] Will be using Plink version unknown
[2018-11-26 13:56:12 INFO] Getting length for chromosome 1
[2018-11-26 13:56:25 INFO] Getting length for chromosome 2
[2018-11-26 13:56:39 INFO] Getting length for chromosome 3
[2018-11-26 13:56:50 INFO] Getting length for chromosome 4
[2018-11-26 13:57:01 INFO] Getting length for chromosome 5
[2018-11-26 13:57:13 INFO] Getting length for chromosome 6
[2018-11-26 13:57:23 INFO] Getting length for chromosome 7
[2018-11-26 13:57:33 INFO] Getting length for chromosome 8
[2018-11-26 13:57:41 INFO] Getting length for chromosome 9
[2018-11-26 13:57:48 INFO] Getting length for chromosome 10
[2018-11-26 13:57:56 INFO] Getting length for chromosome 11
[2018-11-26 13:58:04 INFO] Getting length for chromosome 12
[2018-11-26 13:58:11 INFO] Getting length for chromosome 13
[2018-11-26 13:58:17 INFO] Getting length for chromosome 14
[2018-11-26 13:58:22 INFO] Getting length for chromosome 15
[2018-11-26 13:58:26 INFO] Getting length for chromosome 16
[2018-11-26 13:58:32 INFO] Getting length for chromosome 17
[2018-11-26 13:58:36 INFO] Getting length for chromosome 18
[2018-11-26 13:58:40 INFO] Getting length for chromosome 19
[2018-11-26 13:58:44 INFO] Getting length for chromosome 20
[2018-11-26 13:58:47 INFO] Getting length for chromosome 21
[2018-11-26 13:58:49 INFO] Getting length for chromosome 22
[2018-11-26 13:58:51 ERROR] BioPython >= 1.73 must be installed to read block gzip files.
Traceback (most recent call last):
  File "/Users/lbrueggeman/miniconda3/envs/gtimputation/lib/python3.6/site-packages/pyfaidx/__init__.py", line 341, in __init__
    raise ImportError
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lbrueggeman/miniconda3/envs/gtimputation/bin/genipe-launcher", line 11, in <module>
    sys.exit(main())
  File "/Users/lbrueggeman/miniconda3/envs/gtimputation/lib/python3.6/site-packages/genipe/pipeline/cli.py", line 153, in main
    options=args,
  File "/Users/lbrueggeman/miniconda3/envs/gtimputation/lib/python3.6/site-packages/genipe/pipeline/cli.py", line 1347, in find_exclusion_before_phasing
    reference = Fasta(options.reference, as_raw=True)
  File "/Users/lbrueggeman/miniconda3/envs/gtimputation/lib/python3.6/site-packages/pyfaidx/__init__.py", line 996, in __init__
    build_index=build_index)
  File "/Users/lbrueggeman/miniconda3/envs/gtimputation/lib/python3.6/site-packages/pyfaidx/__init__.py", line 344, in __init__
    "BioPython >= 1.73 must be installed to read block gzip files.")
ImportError: BioPython >= 1.73 must be installed to read block gzip files.```

**Comment by lemieuxl** [comment]
The error comes from `pyfaidx`, not from `genipe`.
I would suggest decompressing the reference file (`hg19.fa.gz`) and re-indexing it.

**Comment by LeoBman** [comment]
Worked, thanks!
